/**
 * workoutToMarkdown — SHRE-01 clipboard export as readable Markdown.
 *
 * Format:
 * # {workout_title}
 *
 * by @{creator_username} · {difficulty} · ~{duration} min
 *
 * Target muscles: {muscles}
 *
 * ## {exercise_name}
 * `{sets} × {reps} @ {rest_seconds}s rest`
 * - {form_cue}
 *
 * ## Superset · rest {N}s
 * ### {inner_name}
 * `{sets} × {reps}`
 *
 * ---
 * AI disclaimer
 */

import type { Workout, RoutineItem } from "@/lib/schema/workout";

const AI_DISCLAIMER =
  "Generated by Exercised — AI-extracted from a YouTube video. Always verify exercises with a qualified trainer.";

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function standardSetSection(
  item: Extract<RoutineItem, { type: "standard_set" }>
): string {
  const lines: string[] = [];
  lines.push(`## ${item.exercise_name}`);
  lines.push(
    `\`${item.sets} × ${item.reps} @ ${item.rest_seconds}s rest\``
  );
  if (item.form_cues && item.form_cues.length > 0) {
    for (const cue of item.form_cues) {
      lines.push(`- ${cue}`);
    }
  }
  return lines.join("\n");
}

export function workoutToMarkdown(w: Workout): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${w.workout_title}`);
  lines.push("");
  lines.push(
    `by @${w.creator_username} · ${capitalize(w.difficulty)} · ~${w.estimated_duration_mins} min`
  );
  lines.push("");

  if (w.target_muscles.length > 0) {
    lines.push(`Target muscles: ${w.target_muscles.join(", ")}`);
    lines.push("");
  }

  // Routine items
  for (const item of w.routine) {
    if (item.type === "standard_set") {
      lines.push(standardSetSection(item));
    } else if (item.type === "superset") {
      lines.push(`## Superset · rest ${item.rest_seconds}s`);
      for (const exercise of item.exercises) {
        lines.push(`### ${exercise.exercise_name}`);
        lines.push(`\`${exercise.sets} × ${exercise.reps}\``);
        if (exercise.form_cues && exercise.form_cues.length > 0) {
          for (const cue of exercise.form_cues) {
            lines.push(`  - ${cue}`);
          }
        }
      }
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(AI_DISCLAIMER);

  return lines.join("\n");
}
