/**
 * workoutToPlainText — SHRE-02 clipboard export for Notes / WhatsApp.
 *
 * Format: title on line 1, creator on line 2, metadata, then numbered
 * exercise list with no markdown markers.
 */

import type { Workout, RoutineItem } from "@/lib/schema/workout";

const AI_DISCLAIMER =
  "Generated by Exercised — AI-extracted from a YouTube video. Always verify exercises with a qualified trainer.";

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function workoutToPlainText(w: Workout): string {
  const lines: string[] = [];

  // Header — no markdown markers
  lines.push(w.workout_title);
  lines.push(`by @${w.creator_username}`);
  lines.push("");
  lines.push(
    `${capitalize(w.difficulty)} · ~${w.estimated_duration_mins} min`
  );

  if (w.target_muscles.length > 0) {
    lines.push(`Target muscles: ${w.target_muscles.join(", ")}`);
  }
  lines.push("");

  // Numbered exercise list
  let exerciseNumber = 1;
  for (const item of w.routine) {
    if (item.type === "standard_set") {
      lines.push(
        `${exerciseNumber}. ${item.exercise_name}`
      );
      lines.push(
        `    ${item.sets} × ${item.reps} @ ${item.rest_seconds}s rest`
      );
      if (item.form_cues && item.form_cues.length > 0) {
        lines.push("    Form cues:");
        for (const cue of item.form_cues) {
          lines.push(`        - ${cue}`);
        }
      }
      lines.push("");
      exerciseNumber++;
    } else if (item.type === "superset") {
      lines.push(`${exerciseNumber}. Superset (rest ${item.rest_seconds}s)`);
      const letters = "abcdefghijklmnopqrstuvwxyz";
      item.exercises.forEach((exercise, i) => {
        const letter = letters[i] ?? String(i + 1);
        lines.push(`    ${letter}) ${exercise.exercise_name} — ${exercise.sets} × ${exercise.reps}`);
        if (exercise.form_cues && exercise.form_cues.length > 0) {
          lines.push("        Form cues:");
          for (const cue of exercise.form_cues) {
            lines.push(`            - ${cue}`);
          }
        }
      });
      lines.push("");
      exerciseNumber++;
    }
  }

  // Footer
  lines.push(AI_DISCLAIMER);

  return lines.join("\n");
}
